project_id = "zoxqjjuokxiyxusqapvv"

[functions.send-notification-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-notification-email/deno.json"
entrypoint = "./functions/send-notification-email/index.ts"

[functions.delete-user]
enabled = true
verify_jwt = true
entrypoint = "./functions/delete-user/index.ts"
