export interface ExerciseCategory {
  id: number;
  name: string;
  category: string;
}

export const EXERCISE_CATEGORIES: ExerciseCategory[] = [
  { id: 1, name: "Abs", category: "Abs" },
  { id: 2, name: "Activation Exercises", category: "Activation Exercises" },
  { id: 3, name: "Back", category: "Back" },
  { id: 4, name: "Biceps", category: "Biceps" },
  { id: 5, name: "Chest", category: "Chest" },
  { id: 6, name: "Compound Exercises", category: "Compound Exercises" },
  { id: 7, name: "Cool Down", category: "Cool Down" },
  { id: 8, name: "Core", category: "Core" },
  { id: 9, name: "Corrective Exercises", category: "Corrective Exercises" },
  { id: 10, name: "Full Body", category: "Full Body" },
  { id: 11, name: "Leg Day", category: "Leg Day" },
  { id: 12, name: "Glutes", category: "Glutes" },
  { id: 13, name: "Hamstrings", category: "Hamstrings" },
  { id: 14, name: "Inner Thighs", category: "Inner Thighs" },
  { id: 15, name: "Lateral Thigh", category: "Lateral Thigh" },
  { id: 16, name: "Quads", category: "Quads" },
  { id: 17, name: "Pull Day", category: "Pull Day" },
  { id: 18, name: "Push Day", category: "Push Day" },
  { id: 19, name: "Senior Fitness", category: "Senior Fitness" },
  { id: 20, name: "Shoulders", category: "Shoulders" },
  { id: 21, name: "Stability Ball", category: "Stability Ball" },
  { id: 22, name: "Stretching", category: "Stretching" },
  { id: 23, name: "Legs", category: "Legs" },
  { id: 24, name: "Circuit Training", category: "Circuit Training" },
  { id: 25, name: "Triceps", category: "Triceps" },
  { id: 26, name: "Cardio", category: "Cardio" },
  { id: 27, name: "HIIT", category: "HIIT" },
  { id: 28, name: "Low Impact Cardio", category: "Low Impact Cardio" },
  { id: 29, name: "High Intensity Training", category: "High Intensity Training" },
  { id: 30, name: "Functional Fitness", category: "Functional Fitness" },
  { id: 31, name: "Mobility", category: "Mobility" },
  { id: 32, name: "Flexibility", category: "Flexibility" },
  { id: 33, name: "Balance Training", category: "Balance Training" },
  { id: 34, name: "Posture Correction", category: "Posture Correction" },
  { id: 35, name: "Pilates", category: "Pilates" },
  { id: 36, name: "Warm-Up", category: "Warm-Up" },
  { id: 37, name: "Cool Down Routine", category: "Cool Down Routine" },
  { id: 38, name: "Bodyweight Training", category: "Bodyweight Training" },
  { id: 39, name: "Resistance Band", category: "Resistance Band" },
  { id: 40, name: "Dumbbell Workouts", category: "Dumbbell Workouts" },
  { id: 41, name: "Barbell Training", category: "Barbell Training" },
  { id: 42, name: "Kettlebell Training", category: "Kettlebell Training" },
  { id: 43, name: "Smith Machine", category: "Smith Machine" },
  { id: 44, name: "Cable Machine", category: "Cable Machine" },
  { id: 45, name: "TRX Suspension", category: "TRX Suspension" },
  { id: 46, name: "Medicine Ball", category: "Medicine Ball" },
  { id: 47, name: "Battle Rope", category: "Battle Rope" },
  { id: 48, name: "Plyometrics", category: "Plyometrics" },
  { id: 49, name: "Agility Training", category: "Agility Training" },
  { id: 50, name: "Speed Training", category: "Speed Training" },
  { id: 51, name: "Power Training", category: "Power Training" },
  { id: 52, name: "Strength Training", category: "Strength Training" },
  { id: 53, name: "Muscle Building", category: "Muscle Building" },
  { id: 54, name: "Weight Loss", category: "Weight Loss" },
  { id: 55, name: "Fat Burning", category: "Fat Burning" },
  { id: 56, name: "Lean Muscle", category: "Lean Muscle" },
  { id: 57, name: "Body Recomposition", category: "Body Recomposition" },
  { id: 58, name: "Endurance", category: "Endurance" },
  { id: 59, name: "Athletic Performance", category: "Athletic Performance" },
  { id: 60, name: "Sports Conditioning", category: "Sports Conditioning" },
  { id: 72, name: "Meditation", category: "Meditation" },
  { id: 73, name: "Breathing Exercises", category: "Breathing Exercises" },
  { id: 74, name: "Mindfulness", category: "Mindfulness" },
  { id: 75, name: "Recovery", category: "Recovery" },
  { id: 76, name: "Foam Rolling", category: "Foam Rolling" },
  { id: 77, name: "Massage Ball", category: "Massage Ball" },
  { id: 78, name: "Neck Mobility", category: "Neck Mobility" },
  { id: 79, name: "Shoulder Mobility", category: "Shoulder Mobility" },
  { id: 80, name: "Hip Mobility", category: "Hip Mobility" },
  { id: 81, name: "Ankle Mobility", category: "Ankle Mobility" },
  { id: 82, name: "Wrist Mobility", category: "Wrist Mobility" },
  { id: 83, name: "Spine Mobility", category: "Spine Mobility" },
  { id: 84, name: "Lower Back Care", category: "Lower Back Care" },
  { id: 85, name: "Sciatica Relief", category: "Sciatica Relief" },
  { id: 86, name: "Joint Health", category: "Joint Health" },
  { id: 87, name: "Bone Strength", category: "Bone Strength" },
  { id: 88, name: "Osteoporosis Fitness", category: "Osteoporosis Fitness" },
  { id: 89, name: "Prenatal Fitness", category: "Prenatal Fitness" },
  { id: 90, name: "Postnatal Fitness", category: "Postnatal Fitness" },
  { id: 91, name: "Women's Fitness", category: "Women's Fitness" },
  { id: 92, name: "Men's Fitness", category: "Men's Fitness" },
  { id: 93, name: "Kids Fitness", category: "Kids Fitness" },
  { id: 94, name: "Teen Fitness", category: "Teen Fitness" },
  { id: 95, name: "Beginner Workouts", category: "Beginner Workouts" },
  { id: 96, name: "Intermediate Workouts", category: "Intermediate Workouts" },
  { id: 97, name: "Advanced Training", category: "Advanced Training" },
  { id: 98, name: "Home Workouts", category: "Home Workouts" },
  { id: 99, name: "Gym Workouts", category: "Gym Workouts" },
  { id: 100, name: "Outdoor Fitness", category: "Outdoor Fitness" },
  { id: 101, name: "Office Workouts", category: "Office Workouts" },
  { id: 102, name: "Travel Workouts", category: "Travel Workouts" },
  { id: 103, name: "Morning Workout", category: "Morning Workout" },
  { id: 104, name: "Evening Workout", category: "Evening Workout" },
  { id: 105, name: "Quick 10-Minute Workout", category: "Quick 10-Minute Workout" },
  { id: 106, name: "15-Minute Workout", category: "15-Minute Workout" },
  { id: 107, name: "20-Minute Workout", category: "20-Minute Workout" },
  { id: 108, name: "30-Minute Workout", category: "30-Minute Workout" },
  { id: 109, name: "45-Minute Workout", category: "45-Minute Workout" },
  { id: 110, name: "60-Minute Workout", category: "60-Minute Workout" },
  { id: 111, name: "Express HIIT", category: "Express HIIT" },
  { id: 112, name: "Tabata", category: "Tabata" },
  { id: 113, name: "EMOM Training", category: "EMOM Training" },
  { id: 114, name: "AMRAP Training", category: "AMRAP Training" },
  { id: 115, name: "Bootcamp", category: "Bootcamp" },
  { id: 116, name: "Military Fitness", category: "Military Fitness" },
  { id: 117, name: "Obstacle Training", category: "Obstacle Training" },
  { id: 118, name: "Farmer Carry", category: "Farmer Carry" },
  { id: 119, name: "Grip Strength", category: "Grip Strength" },
  { id: 120, name: "Functional Core", category: "Functional Core" },
  { id: 121, name: "Rotational Training", category: "Rotational Training" },
  { id: 122, name: "Anti-Rotation", category: "Anti-Rotation" },
  { id: 123, name: "Explosive Core", category: "Explosive Core" },
  { id: 124, name: "Explosive Legs", category: "Explosive Legs" },
  { id: 125, name: "Jump Training", category: "Jump Training" },
  { id: 126, name: "Vertical Jump", category: "Vertical Jump" },
  { id: 127, name: "Sprint Drills", category: "Sprint Drills" },
  { id: 128, name: "Running", category: "Running" },
  { id: 129, name: "Treadmill", category: "Treadmill" },
  { id: 130, name: "Walking", category: "Walking" },
  { id: 131, name: "Hiking", category: "Hiking" },
  { id: 132, name: "Cycling", category: "Cycling" },
  { id: 133, name: "Spin Bike", category: "Spin Bike" },
  { id: 134, name: "Rowing", category: "Rowing" },
  { id: 146, name: "Senior Strength", category: "Senior Strength" },
  { id: 147, name: "Senior Balance", category: "Senior Balance" },
  { id: 148, name: "Fall Prevention", category: "Fall Prevention" },
  { id: 149, name: "Functional Aging", category: "Functional Aging" },
  { id: 150, name: "Mobility for Seniors", category: "Mobility for Seniors" },
  { id: 156, name: "Corrective Posture", category: "Corrective Posture" },
  { id: 157, name: "Desk Stretch", category: "Desk Stretch" },
  { id: 158, name: "Neck Stretch", category: "Neck Stretch" },
  { id: 159, name: "Hamstring Stretch", category: "Hamstring Stretch" },
  { id: 160, name: "Quad Stretch", category: "Quad Stretch" },
  { id: 161, name: "Glute Stretch", category: "Glute Stretch" },
  { id: 162, name: "Calf Stretch", category: "Calf Stretch" },
  { id: 163, name: "Chest Stretch", category: "Chest Stretch" },
  { id: 164, name: "Shoulder Stretch", category: "Shoulder Stretch" },
  { id: 165, name: "Back Stretch", category: "Back Stretch" },
  { id: 166, name: "Hip Stretch", category: "Hip Stretch" },
  { id: 167, name: "Mobility Flow", category: "Mobility Flow" },
  { id: 168, name: "Dynamic Warm-Up", category: "Dynamic Warm-Up" },
  { id: 169, name: "Static Stretching", category: "Static Stretching" },
  { id: 170, name: "Cool Down Flow", category: "Cool Down Flow" },
  { id: 171, name: "Fitness Challenge", category: "Fitness Challenge" },
  { id: 172, name: "30-Day Challenge", category: "30-Day Challenge" },
  { id: 173, name: "90-Day Transformation", category: "90-Day Transformation" },
  { id: 174, name: "Weight Gain Program", category: "Weight Gain Program" },
  { id: 175, name: "Strength Challenge", category: "Strength Challenge" },
  { id: 176, name: "Push-Up Challenge", category: "Push-Up Challenge" },
  { id: 177, name: "Pull-Up Challenge", category: "Pull-Up Challenge" },
  { id: 178, name: "Squat Challenge", category: "Squat Challenge" },
  { id: 179, name: "Plank Challenge", category: "Plank Challenge" },
  { id: 180, name: "Core Challenge", category: "Core Challenge" },
  { id: 181, name: "Fat Loss Challenge", category: "Fat Loss Challenge" },
  { id: 182, name: "Nutrition Coaching", category: "Nutrition Coaching" },
  { id: 183, name: "Meal Planning", category: "Meal Planning" },
  { id: 184, name: "Healthy Recipes", category: "Healthy Recipes" },
  { id: 185, name: "Hydration", category: "Hydration" },
  { id: 186, name: "Supplement Education", category: "Supplement Education" },
  { id: 187, name: "Fitness Assessment", category: "Fitness Assessment" },
  { id: 188, name: "BMI & Body Fat", category: "BMI & Body Fat" },
  { id: 189, name: "Progress Tracking", category: "Progress Tracking" },
  { id: 190, name: "Body Measurements", category: "Body Measurements" },
  { id: 191, name: "Workout Recovery", category: "Workout Recovery" },
  { id: 192, name: "Sleep & Recovery", category: "Sleep & Recovery" },
  { id: 193, name: "Stress Management", category: "Stress Management" },
  { id: 194, name: "Mental Wellness", category: "Mental Wellness" },
  { id: 195, name: "Lifestyle Coaching", category: "Lifestyle Coaching" },
  { id: 196, name: "Personal Training", category: "Personal Training" },
  { id: 197, name: "Group Training", category: "Group Training" },
  { id: 198, name: "Live Workout Sessions", category: "Live Workout Sessions" },
  { id: 199, name: "On-Demand Video Library", category: "On-Demand Video Library" },
  { id: 200, name: "AI Personalized Workout", category: "AI Personalized Workout" },
];
