export interface ExerciseCategory {
  id: number;
  name: string;
  category: string;
}

export const EXERCISE_CATEGORIES: ExerciseCategory[] = [
  { id: 1, name: "Weight Loss", category: "Weight Loss" },
  { id: 2, name: "Fat Burning", category: "Fat Burning" },
  { id: 3, name: "Muscle Gain", category: "Muscle Gain" },
  { id: 4, name: "Strength Training", category: "Strength Training" },
  { id: 5, name: "Bodybuilding", category: "Bodybuilding" },
  { id: 6, name: "Functional Training", category: "Functional Training" },
  { id: 7, name: "HIIT Workouts", category: "HIIT Workouts" },
  { id: 8, name: "Cardio Training", category: "Cardio Training" },
  { id: 9, name: "Endurance Training", category: "Endurance Training" },
  { id: 10, name: "Circuit Training", category: "Circuit Training" },
  { id: 11, name: "Core Strength", category: "Core Strength" },
  { id: 12, name: "Abs Workouts", category: "Abs Workouts" },
  { id: 13, name: "Full Body Workouts", category: "Full Body Workouts" },
  { id: 14, name: "Upper Body", category: "Upper Body" },
  { id: 15, name: "Lower Body", category: "Lower Body" },
  { id: 16, name: "Chest Workouts", category: "Chest Workouts" },
  { id: 17, name: "Back Workouts", category: "Back Workouts" },
  { id: 18, name: "Shoulder Workouts", category: "Shoulder Workouts" },
  { id: 19, name: "Arm Workouts", category: "Arm Workouts" },
  { id: 20, name: "Biceps Training", category: "Biceps Training" },
  { id: 21, name: "Triceps Training", category: "Triceps Training" },
  { id: 22, name: "Forearm Training", category: "Forearm Training" },
  { id: 23, name: "Leg Workouts", category: "Leg Workouts" },
  { id: 24, name: "Glute Training", category: "Glute Training" },
  { id: 25, name: "Hamstring Exercises", category: "Hamstring Exercises" },
  { id: 26, name: "Quadriceps Exercises", category: "Quadriceps Exercises" },
  { id: 27, name: "Calf Exercises", category: "Calf Exercises" },
  { id: 28, name: "Hip Mobility", category: "Hip Mobility" },
  { id: 29, name: "Knee Strengthening", category: "Knee Strengthening" },
  { id: 30, name: "Ankle Mobility", category: "Ankle Mobility" },
  { id: 31, name: "Mobility Training", category: "Mobility Training" },
  { id: 32, name: "Flexibility Training", category: "Flexibility Training" },
  { id: 33, name: "Stretching", category: "Stretching" },
  { id: 34, name: "Dynamic Stretching", category: "Dynamic Stretching" },
  { id: 35, name: "Static Stretching", category: "Static Stretching" },
  { id: 36, name: "Warm-Up Exercises", category: "Warm-Up Exercises" },
  { id: 37, name: "Cool-Down Exercises", category: "Cool-Down Exercises" },
  { id: 38, name: "Balance Training", category: "Balance Training" },
  { id: 39, name: "Stability Training", category: "Stability Training" },
  { id: 40, name: "Coordination Drills", category: "Coordination Drills" },
  { id: 41, name: "Agility Training", category: "Agility Training" },
  { id: 42, name: "Speed Training", category: "Speed Training" },
  { id: 43, name: "Plyometric Exercises", category: "Plyometric Exercises" },
  { id: 44, name: "Explosive Power", category: "Explosive Power" },
  { id: 45, name: "Olympic Lifting", category: "Olympic Lifting" },
  { id: 46, name: "Powerlifting", category: "Powerlifting" },
  { id: 47, name: "CrossFit", category: "CrossFit" },
  { id: 48, name: "Kettlebell Training", category: "Kettlebell Training" },
  { id: 49, name: "Dumbbell Workouts", category: "Dumbbell Workouts" },
  { id: 50, name: "Barbell Training", category: "Barbell Training" },
  { id: 51, name: "Resistance Band Training", category: "Resistance Band Training" },
  { id: 52, name: "Bodyweight Exercises", category: "Bodyweight Exercises" },
  { id: 53, name: "TRX Suspension Training", category: "TRX Suspension Training" },
  { id: 54, name: "Battle Rope Training", category: "Battle Rope Training" },
  { id: 55, name: "Medicine Ball Exercises", category: "Medicine Ball Exercises" },
  { id: 56, name: "Sandbag Training", category: "Sandbag Training" },
  { id: 57, name: "Bosu Ball Training", category: "Bosu Ball Training" },
  { id: 58, name: "Stability Ball Exercises", category: "Stability Ball Exercises" },
  { id: 59, name: "Foam Rolling", category: "Foam Rolling" },
  { id: 60, name: "Recovery Workouts", category: "Recovery Workouts" },
  { id: 61, name: "Home Workouts", category: "Home Workouts" },
  { id: 62, name: "Gym Workouts", category: "Gym Workouts" },
  { id: 63, name: "Outdoor Workouts", category: "Outdoor Workouts" },
  { id: 64, name: "Office Workouts", category: "Office Workouts" },
  { id: 65, name: "Travel Workouts", category: "Travel Workouts" },
  { id: 66, name: "Beginner Fitness", category: "Beginner Fitness" },
  { id: 67, name: "Intermediate Fitness", category: "Intermediate Fitness" },
  { id: 68, name: "Advanced Fitness", category: "Advanced Fitness" },
  { id: 69, name: "Senior Fitness", category: "Senior Fitness" },
  { id: 70, name: "Kids Fitness", category: "Kids Fitness" },
  { id: 71, name: "Teen Fitness", category: "Teen Fitness" },
  { id: 72, name: "Women's Fitness", category: "Women's Fitness" },
  { id: 73, name: "Men's Fitness", category: "Men's Fitness" },
  { id: 74, name: "Prenatal Fitness", category: "Prenatal Fitness" },
  { id: 75, name: "Postnatal Fitness", category: "Postnatal Fitness" },
  { id: 76, name: "Yoga", category: "Yoga" },
  { id: 77, name: "Power Yoga", category: "Power Yoga" },
  { id: 78, name: "Hatha Yoga", category: "Hatha Yoga" },
  { id: 79, name: "Vinyasa Yoga", category: "Vinyasa Yoga" },
  { id: 80, name: "Ashtanga Yoga", category: "Ashtanga Yoga" },
  { id: 81, name: "Yin Yoga", category: "Yin Yoga" },
  { id: 82, name: "Meditation", category: "Meditation" },
  { id: 83, name: "Breathing Exercises", category: "Breathing Exercises" },
  { id: 84, name: "Mindfulness Training", category: "Mindfulness Training" },
  { id: 92, name: "Cycling Workouts", category: "Cycling Workouts" },
  { id: 93, name: "Rowing Exercises", category: "Rowing Exercises" },
  { id: 95, name: "Sports Performance", category: "Sports Performance" },
  { id: 96, name: "Athletic Conditioning", category: "Athletic Conditioning" },
  { id: 98, name: "Injury Prevention", category: "Injury Prevention" },
  { id: 99, name: "Posture Correction", category: "Posture Correction" },
  { id: 100, name: "Daily Fitness Challenges", category: "Daily Fitness Challenges" },
];
