// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function cleanEnvVar(val: string | undefined): string | undefined {
  if (!val) return undefined;
  let cleaned = String(val).trim();
  cleaned = cleaned.replace(/%(0a|0d|20)/gi, '');
  try {
    cleaned = decodeURIComponent(cleaned);
  } catch (e) {
    // ignore
  }
  return cleaned
    .replace(/%(0a|0d|20)/gi, '')
    .replace(/[\r\n\t\s\u200B-\u200D\uFEFF]/g, '')
    .trim();
}

const DEFAULT_URL = "https://zoxqjjuokxiyxusqapvv.supabase.co";
const DEFAULT_KEY = "sb_publishable_si6AX2a9wvUOanT9rzYO3g_Z00nBcWv";

const rawUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const rawKey = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY) as string | undefined;

const cleanedUrl = cleanEnvVar(rawUrl);
const cleanedKey = cleanEnvVar(rawKey);

const SUPABASE_URL = cleanedUrl || DEFAULT_URL;
const SUPABASE_PUBLISHABLE_KEY = cleanedKey || DEFAULT_KEY;

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);